### ISSUE TITLE
Issue installing croogo/app

### ISSUE THREAD

**Issue by harvyde** [croogo/app#22]
I've error installing croogo. Half of the tables are being created in database, then it shows error below.

https://github.com/croogo/app

Notice: PDO::__construct(): send of 131 bytes failed with errno=32 Broken pipe in /Users/harvinder/sites/project.com_3.0/app/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/MysqlAdapter.php on line 113
There was a problem connecting to the database: SQLSTATE[HY000] [2006] MySQL server has gone away
InvalidArgumentException
Documentation API
/Users/harvinder/sites/project.com_3.0/app/webroot/index.php toggle arguments
// Bind your application to the server.
$server = new Server(new Application(dirname(__DIR__) . '/config'));
// Run the request/response through the application and emit the response.
$server->emit($server->run());
If you want to customize this error message, create src/Template/Error/error500.ctp

toggle vendor stack frames
⟩ Phinx\Db\Adapter\MysqlAdapter->connect
ROOT/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php, line 238
⟩ Phinx\Db\Adapter\PdoAdapter->getConnection
ROOT/vendor/cakephp/migrations/src/CakeAdapter.php, line 57
⟩ Migrations\CakeAdapter->__construct
ROOT/vendor/cakephp/migrations/src/Migrations.php, line 384
⟩ Migrations\Migrations->setAdapter
ROOT/vendor/cakephp/migrations/src/Migrations.php, line 361
⟩ Migrations\Migrations->getManager
ROOT/vendor/cakephp/migrations/src/Migrations.php, line 305
⟩ Migrations\Migrations->run
ROOT/vendor/cakephp/migrations/src/Migrations.php, line 142
⟩ Migrations\Migrations->status
ROOT/vendor/croogo/croogo/Core/src/Plugin.php, line 521
⟩ Croogo\Core\Plugin->needMigration
ROOT/vendor/croogo/croogo/Core/src/Plugin.php, line 540
⟩ Croogo\Core\Plugin->migrate
ROOT/vendor/croogo/croogo/Install/src/InstallManager.php, line 197
⟩ Croogo\Install\InstallManager->runMigrations
ROOT/vendor/croogo/croogo/Install/src/InstallManager.php, line 154
⟩ Croogo\Install\InstallManager->setupDatabase
ROOT/vendor/croogo/croogo/Install/src/Controller/InstallController.php, line 192
⟩ Croogo\Install\Controller\InstallController->data
CORE/src/Controller/Controller.php, line 440
⟩ Cake\Controller\Controller->invokeAction
CORE/src/Http/ActionDispatcher.php, line 119
⟩ Cake\Http\ActionDispatcher->_invoke
CORE/src/Http/ActionDispatcher.php, line 93
⟩ Cake\Http\ActionDispatcher->dispatch
CORE/src/Http/BaseApplication.php, line 109
⟩ Cake\Http\BaseApplication->__invoke
CORE/src/Http/Runner.php, line 65
⟩ Cake\Http\Runner->__invoke
ROOT/vendor/croogo/croogo/Install/src/Middleware/InstallMiddleware.php, line 24
⟩ Croogo\Install\Middleware\InstallMiddleware->__invoke
CORE/src/Http/Runner.php, line 65
⟩ Cake\Http\Runner->__invoke
CORE/src/Routing/Middleware/RoutingMiddleware.php, line 104
⟩ Cake\Routing\Middleware\RoutingMiddleware->__invoke
CORE/src/Http/Runner.php, line 65
⟩ Cake\Http\Runner->__invoke
CORE/src/Routing/Middleware/AssetMiddleware.php, line 88
⟩ Cake\Routing\Middleware\AssetMiddleware->__invoke
CORE/src/Http/Runner.php, line 65
⟩ Cake\Http\Runner->__invoke
CORE/src/Error/Middleware/ErrorHandlerMiddleware.php, line 98
⟩ Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke
CORE/src/Http/Runner.php, line 65
⟩ Cake\Http\Runner->__invoke
ROOT/vendor/cakephp/debug_kit/src/Middleware/DebugKitMiddleware.php, line 52
⟩ DebugKit\Middleware\DebugKitMiddleware->__invoke
CORE/src/Http/Runner.php, line 65
⟩ Cake\Http\Runner->__invoke
CORE/src/Http/Runner.php, line 51
⟩ Cake\Http\Runner->run
CORE/src/Http/Server.php, line 81
⟩ Cake\Http\Server->run
ROOT/webroot/index.php, line 40

**Comment by rchavik** [comment]
Please try again with recent version or 4.x
